apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:I9r3Tvh2QO4t9qCgklsQh2ffHzaQ6edeu/Q7O58BVmZFFiqn4yTlnGNwZKq4TJHaKOZDols=,iv:ZedLmb78n0jaX/caLdifnOPlPZczLxcvuCgmr1N65ow=,tag:aKpDY/9TappG0ZjHrro2og==,type:str]
sops:
  age:
    - recipient: age10tnmsw8l3xsg8ym5ed4x8zk606jq77jzudrehky98vf9jyw37gjqfn67fa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QVJ5T2p6N0M3UUNrZk1i
        bGFDM29kaFd0ZVFobFdieE9vWHliVVIrTkZrCnNSZjZaOHYzRVNGNW1sN2xJV3Yr
        MEJVaVdyU0xIcWc1WmpHS0JNU2ZKbGcKLS0tIEd4Q1I4YXpvZFNxRjNpa1hpK0hQ
        bzJsU3lxSTZRUDBHcXVkbFUySjd6NVkKu24KhBoKJCr7OGvO/TTHGyL2FsmPH0+J
        H+Xq4Eo4Mu1dnxYqhAmre2caYN+XOohFoJA1DhyAUlSz/hfgdHu1Fw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T14:15:46Z"
  mac: ENC[AES256_GCM,data:xVQKL6UrQp5KdJCnu89SsgBiUawRv5WoxM8fdciNE7/eYeiogcDQMSY2gw24tPrWFukvAdeHO9b0Saf1T29GRBfaW0/EMAlTYhsS6GqpLW6zondFbbto4AADLfC954L9VDYZqGVkDtqvRjBVWPZ3/oci0IOa49Q0BuwsW/mfzAw=,iv:Do0Z4N0gImAM6DbxXVzL3pnaQSV+mnmxhSG6WAeYfyU=,tag:8x5/p+Fb3r3vRZhQ1Hp6SQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
