apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Tb9JYMehdMZ8J9RLUBGAe6flu1kOfGc6g3r0fUJsr1eX1IxaypWGNvLxy+joQnqvbRh3Gik=,iv:/fgrFqyzErLNkwiARFXUKQ0KSZ3QlM7byUThBADNQ2A=,tag:HEptTLcnguF8Pzaqrw0dDg==,type:str]
sops:
  age:
    - recipient: age10tnmsw8l3xsg8ym5ed4x8zk606jq77jzudrehky98vf9jyw37gjqfn67fa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOTk5ZS9pN2VxUnJCSnFH
        UUlmSEY4cDlEZktySHJJdWxTOFd5NkxuSzNJCm96RHdIVm0vcm9nc0o4M25XSVBu
        aTloN2hveXc5b3FsWFNsRFBtckk5RmMKLS0tIHdDS1p2am00d1loaVFDdUNuOXBV
        SW9pNmdlTmtBYjFEazVXU0J0TjZlWEUKTmeAlMrfkxhDhogwZ5GKhDDjq699fgb/
        X7vO4TTixjVxmCfnO+lhVel/2M8lLG0WsDR8TyqWcybnazr97WWPig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T12:31:23Z"
  mac: ENC[AES256_GCM,data:xiYGdnhXOkIsHZ+fVbJQFnYFW6cdE2JXnH9PvCMy5JnVeE1pBFJyDpEXqeiEynTNrc4HIhcjwTNnHj7x9tiKhYIzVjgrkxtRgKOsVaBmo8XsqWgSUfu2n2Cd/r+90z9WCrt0VFgvl3fE+8jh0ollLP0FZc2r9O3nRDJFkiQApmY=,iv:MDf0Gaa/OiZHvEuMd21OABzARG5NXu5OISajiQHwQGk=,tag:BzYB77gATiFDVGI6H9ncug==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
