apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:VxEeYf3QfVc+bq7fw5dSU92vSOEBEiAs60Iwiyw74xjLnvGS92OqS2N7kukPhTDq8vcG+Lk=,iv:TOQROmMn91M3mSn9jbCd4x6ZLz3jVXY0s4YtmlOKyzY=,tag:3YrmzDFRRYiGqwpQkMq3aQ==,type:str]
sops:
  age:
    - recipient: age10tnmsw8l3xsg8ym5ed4x8zk606jq77jzudrehky98vf9jyw37gjqfn67fa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMUFGQXcwbUNjRGhoRUNQ
        TysyY3k0K1BjOWNvRUpBbmNvVkpTWDZycVZBCk5DKzEwampTN0FQRy8vOCtHVEF1
        WXE1R1R2bVh0T3lwR2dUekZMbXJnN3cKLS0tIDRhQjB1cytPTDlvYnA3M3o2K3hq
        ak9TaWo5eGhwWWZRZGVYOXhhMnRyb28KcvHtWSMDyVoOUPuqN4m9kEMEst5YBIpL
        ksFQsu04Zd5tUXzJMMUzQU9MGmZjz48sI3Htw6CQgxhKR1NAq9xNUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T12:20:29Z"
  mac: ENC[AES256_GCM,data:1e3uMlo70aFF3rjtOWA1nBy5/62LnFuYNkl1N1qHObMcAnjjKoD7EHZlMIc9gUFu8kAbwC6mPmMVPNaGpEow6VNaPA7esBZiyVQlXggNPsceRMgMv1ox0PT+2XGqdKFclH4Zdv+32UAyjP+lxo2mi6fPmNYJB8jkKMBWHQTrgRs=,iv:W+Ca1pm/XfDeSnxVNmL3k7NHPN1srJU3MJSgXp7vkxQ=,tag:FsR6SPyL/s9y7FpjJ4Uczw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
