apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:rbH8eEUMcUav96mf,iv:4J2JDwYCC+DaQTBz4tYRanfjSNLt/gV2zdcnduuKVnc=,tag:3heYALqqlbT7o2yi0akNbw==,type:str]
sops:
  age:
    - recipient: age10tnmsw8l3xsg8ym5ed4x8zk606jq77jzudrehky98vf9jyw37gjqfn67fa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOVVTVGFhakdxY2xQRjFL
        dVkvckU2cFlpM1hDeEUxZks1eWVEb3R2Nm00CnE2ZGFQcmFnOFFlREVBNXFHTHV5
        T0dERnl5RFdoeUZ2NDNaU1EyNys5ZEkKLS0tIHJIU2d4UlZZSyt6VHRaWVZta2Q5
        Umo2cHRYWnpaZDlzWVpGTXVzN3NLNWMKeTrhg3o7mLKzrF6f9W9mXhFKnn0urwtn
        b2LoQkZvpnpciFIlL3FHw6GgIyz6vWHOc1RAgTtt6RXA95dJgS8avA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T12:31:24Z"
  mac: ENC[AES256_GCM,data:QKErc7vvpDgR6CrUPZeZfE8BoSb0XtJkIOWGrHQTVzUbVY+0xmeHCsyK7fdZ5O6iutbEuMNJC0k6Cr8TVwcJnbGKqzY2/QX34gILPgVCwpPKDwcLBwFO++YNssAlYDU574KdA9naEhD6s+2z6wDDwYFaEqQ8XKEdjJUxhxlgdP0=,iv:6AUAsm58MXkWf9/iupgl1NNNBNqoSgakbnAASrDbT04=,tag:CKtvGh2hVR/g4L4LZURHVQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
