apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:VZ+oRkeCR5sW2fFB,iv:TstVJY32YMdFxX2C3eTzj4wlNmbfm44aVHmAzo3YbOk=,tag:XGgpuEW5gZCzRBp9/2shAg==,type:str]
sops:
  age:
    - recipient: age10tnmsw8l3xsg8ym5ed4x8zk606jq77jzudrehky98vf9jyw37gjqfn67fa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZ3cyY1U2dFgyUjRDcVMw
        Vkx1amZyTm1Da1pycXZPVncrcDExcFZBZXdVCk9CUjUrdHV0MmVLUTVVaEF2eHFJ
        ZVdvN29lQ1hNa0lGVUxrZFFnalNMWWMKLS0tIDlCTmRuMU55cW85c2FPZVdvNFlm
        aWFaS0YzaXhHbkZFOEpXSGFMZlFoeU0K3yyCDPdX8srOrDynbrhpFHJZMYEKAU6n
        4KzSYev1Nx7TlyfLc/HM9zp+o+DxyjHmyJsASDA5gma9F5ZPR6E6SQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T14:15:46Z"
  mac: ENC[AES256_GCM,data:/2uull85VjjRDebjmvvTZrjW1hFEehqb3ghYNxXQxEGLuesLkkZgbgXGO+SRnqpdMsSM79VKW/wLyaxPv/pvnUoukrqXjEwZfKuLtUXtudEboqwkydOT1NlLBvUUWcv4G8/22/rugPxFBrWZ9MxDsi8VxSiBzrzy7+RAxUSQR5U=,iv:UZLaaPWWxFZHfwHecDoe0EPGyFGuVh/+MfOqsxMf/e4=,tag:diTZtSUW0fqIGSNW9U//lw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
