apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Q+9s3asoilWJbPaM,iv:AhoSHfEnrNulHiwcmBx633cZFh+C89m3VT+gY80T5xo=,tag:kiD9lWKwVRIHWTj6zQlMgQ==,type:str]
sops:
  age:
    - recipient: age10tnmsw8l3xsg8ym5ed4x8zk606jq77jzudrehky98vf9jyw37gjqfn67fa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVHhhcTV4V0xFSlVKaC9X
        MkFqRlZxbXJJbGtuMVYvU3VtNyszdGFTbFU0ClBnWVVQN3ZEdHJNOFRVMHJqa1Ux
        YmxnSG1GOTNkS1JzWllBYzViU1JqeGMKLS0tIGxiWTlsdmhFN0Zza3RlcmhSTHZk
        SHFjS21Lbi9FSDZ6d2pTVjNTMHYzMGMKkeC6TmHp6NY/77VlM/O3T87ALoH44QUi
        50jJoPmRwDz3wJwU5CJglCuFnwTNMuf+TYg3BShpdnIvLtc1ITl/xA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T12:20:29Z"
  mac: ENC[AES256_GCM,data:SQDFc3S2cV8e0SZ4z1RBwdkphsSzmgi9G/GWrGox5mhRMHwL28D2jy6KPSl6Ephd+Vs0/WOMvaXVXo0IGeM4O6n1m1T8/VCcw98ovo8sKG2QKbJfnZQWoy+aKN+s2jiItpLpSHMIl8dTYYFScevqa81sskT40IWDRMAzM6bkpH8=,iv:iXEH+3GVkzlW4LJv4f7RGV/ARmAkk+Jx7PdGYtahrIs=,tag:2wmPvhZ5pGzemyxWQfndlA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
