apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Edve50ACvvoX0cDD8m4uiluCDNTvEnLjOyzC2B+ikCg=,iv:yCNL78aPIcpCbbMsRfbFgIiJi4GeaZZTZ6TADdIh3TA=,tag:St+yy67cQultrO4X3UWy6g==,type:str]
sops:
  age:
    - recipient: age10tnmsw8l3xsg8ym5ed4x8zk606jq77jzudrehky98vf9jyw37gjqfn67fa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NXMxeTFMNWp2cUwycVJy
        Qm8wT3A3d0xnRE1TUGpWWHIvdDJ5MUtSaUdZCmgralZTRWZzdDd6ODBkclpYTzls
        QkZER0FWeHBEbzFsWUdqSzhEbFNKQ0UKLS0tIGNqNlNGRHUrc1Nkd2J4L29PZEps
        SndJYXZwdHZmRUtEckJaazVhZUFXeWcKFrwnPpcB7RhK6+z2d1hVg2RjmModMnLS
        5rVXKcBu58C4JTZQbXunLSASxbmdp4WiB5lKKhts9X/l2ORRBfSRjw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T12:31:23Z"
  mac: ENC[AES256_GCM,data:45acuWM4bFRLmCr3OHxuC6qpqzMp/yIyN7JpV4uya4k2UEvWHhNIYDZoKDGUnVKlXu42v6vSpjSOCGIrDatcVQlhK6faxWFCzoN1VH3+cu6pVrBGgwSAuhjc8h2Wd0k0kZzfVsyQhk8C4NnnFquYa2CZyTEf3nteC2snP3GlCEQ=,iv:xbDzM2BG6ZPdxhQoFZsmR54Q3WOi/dAec1qmTXCZ6Yw=,tag:qspPfJrXOK6iaZun1QOn+Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
