apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:IIWy6pFHkFc+/fj9uVxTKOZGXqIlTQVbdT4omgwAt94=,iv:DlgxF/kWsT3c2C4QkVCSOmckvnvMpC655lbuuTSCohQ=,tag:uYplFKv1Se1+6vq5U7WgpA==,type:str]
sops:
  age:
    - recipient: age10tnmsw8l3xsg8ym5ed4x8zk606jq77jzudrehky98vf9jyw37gjqfn67fa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRjBrY2hCM3pCaTVyMWpH
        TnB2akthTVhSeFh5czI5WktGWEU4SVRGWWxnCjAwMlNxVEJvRitXUzhrc0lCZGV4
        eTh6SENaZWFiL1BEdFpZYlNnUHd1S2cKLS0tIFZIVHhWWmVYeU5oMU1tVEtTMXE1
        Ry9ocVIyaUdTZk41Zlg0cHBRekVndTgKqn224vj+sAfdUnUvTW/O/WBEdFGyoEl0
        n0G17R/lW73qSA6CI9Kzz342mNixfETfkfIplB7fusFRpmG9Eso12g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T12:17:24Z"
  mac: ENC[AES256_GCM,data:UU6l8dkoNK4WITI+8hUoc4wtPjY7yUJMsJMMH4NElwif8g7ZdChAxUwreiK7qYryjflPY6VYFjXq/1l1qihlKmZdvq18M8GrnEbt0bzRX2w4qKlJzs9wC73ZDoUIcTezTOOjZbPLcF7AvUdwbLvN8olgamzGftVFp6vtEsDkl0Y=,iv:yT1Ao0eACOtY8ZpJ78wH5ovyNlAGk4zosZyB7008gdI=,tag:IElv2E6zGpWzbwPcjaRC7w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
