apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:NiTuiW8vobQHxJQjBoeszC6zNmAvLtUSmezTxzPtR9s=,iv:gIxgYFaUKXCIxYCuspu72jxXA0Gfm1hEiBHu8/J0QUo=,tag:I5RkmplR34cBptDCZi4aUg==,type:str]
sops:
  age:
    - recipient: age10tnmsw8l3xsg8ym5ed4x8zk606jq77jzudrehky98vf9jyw37gjqfn67fa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtL1NmbklBNDFkZTZkNHA3
        d3BqT0VXckxOdk9tdmd0U0dXNEI0VmJ2bm5nCmlXV3FteFZDUVI3U1VOU1ZuUmRS
        STNTVWhtM1V4YWJyUjlrSXFLdzdNSE0KLS0tIE1sR2QxSzdpWnhGNFBWby9SNXBH
        VllrM2MrK3RhMktRaFFreDE2dFdWUmsKr0QY1wpCP1j2+M7EdihNGkxQHjtLDBU+
        cwNjRul0oZSEkNjtYFLTd1ajNQxVJ9rN5rFiaSnj3siPZ/BRqVvWGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T14:15:46Z"
  mac: ENC[AES256_GCM,data:kK27aw6NwOih4srEKGS9azNVErQgcdnEpLpQtm+KlshNPHuvsteZP8mZ6+MaGCDZo49RAek1lAVh0cQZsEGzbK27ySGvbHXg+hOGHUX1ZygikJsJpPOEHju2I+br3WR6mIGOKzxTWxF6kDfZmT7y4D0ccMVOfdVDvKUfoedtmwE=,iv:Vxd+2rxVbiu8bZAFFCeyjIStMIIOXy4G0sULKpSQPAk=,tag:pGqayzeOalDti2vL1MFgng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
