apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:7TClqXJfRkkFbJPPWGXTwywll2dR1SoDXbYgrrW4i9n1oFsTLEfF2jnpsWBaQUpAWDF2TWm9ZcmmekxD6wK+bcMy75Cf2ioJyl99l4s++Ui7XJfUeNbOvFZ/BmnFmwXfkwFMo146umRdnfFDeXkT6Tg3bugRC22J8yMA5yAb2sDK4u2uPohBD5dg4gFJBt5QIBkHuPRwl+75egOrR8zUD+ZXhlvaPepYiOIjQz3HwqjcYvl1,iv:lyu8ADd4jC5A17kJiTQLO5por0msLSz/AY+k3McVraY=,tag:d3W8hvF1sW4VGwI96Xmy4w==,type:str]
sops:
  age:
    - recipient: age10tnmsw8l3xsg8ym5ed4x8zk606jq77jzudrehky98vf9jyw37gjqfn67fa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNWNDU2Y4ay9uMVBCZkgv
        YU9LamhVcjhYT1ZFbFM5dGNQeEU1dWhkMWxVCldyUnRNOTcyK2MxeU1xS2E0U1N6
        dTRkWkNIQ2FaczYwMFdDK09rSlo3ZmMKLS0tIFBNb01QWHFQYlprbnZsTXNNZUVv
        cDlreGdKbzFObzl1L25ZWkZxUHFOek0KrMcFhEb0UJiXObwn/TaPqk4BgzibvnTM
        RmJA4pfhkRddGAJb1aS8UBD7/pZpJQtDS1+tFXinIDfm7srGdG7ycQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T14:15:46Z"
  mac: ENC[AES256_GCM,data:0Z1ft1nRZZi2ApTr6o8giPeiDSC41+vcXoLflRRK4IOu39emRi6KWHYN25ZiPp9OynkRzTLbB3eGAvnE2TZEy6BK3MulxxDrbEfONb5w4ESWEgWtd9AuJOccO1W6XZr4Gf2auct5P1LIA/IfUI9zjTmpSpKJok8oUYESAIbxA1A=,iv:wcEtPRtSSODhz9ooWb3Duj6Cswab7wwJG4GEltxBIrI=,tag:1twbtLp6+GUVl40vfd2tsw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
