apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:jTJTjlSAKK/RBkZNpZY8T3Gwu7NLCBHgE5fkyGnTP+2lGmotROzYoAsEe2xikAfZt3gFMB/Vax5zZ70RZetCcEP0oKAktqqKgTZY3r1BCo7ZZH+vMQNDPE3vfhf9a4nGPm1NOH8jV4ybUH3VBXZVVndBcCKmfm2uAOnk2APkc/yqscFV96vY2vwAvQhyZb+XIZv+rfoe1nkpB3KmLf5PKbVO5hKnUPekS+TXzeGkxfmmEPOY,iv:E3Nu7SukrKURbcP/IHvBdwtFhX8EyvTUq2sFU4N2MWQ=,tag:VhWetQjeOauw3lsaJ0DQ7A==,type:str]
sops:
  age:
    - recipient: age10tnmsw8l3xsg8ym5ed4x8zk606jq77jzudrehky98vf9jyw37gjqfn67fa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaU5OY0JWTGRRUVFncnZt
        eVRId0ExeUEzMHZmNmR3NnJpR0o2ZWVMWjEwCnUvYm1qUmZPajNPSVV0RFU4b1Y2
        SW03eFpNeEszRGQ4aFk1RDVmQ3FOZ0UKLS0tIEpUQXFZY0RHSWRBd1NMS083dDVQ
        Ym1YSUY4bGtvdTVKeVc2QjJ1T2h2MzQKo9VnQG4D+fLCEiDujBUuJ5DcOwnvus6/
        6DC9zFPqyG+FvUXOxwh+bFU/ifmbSY+zP1cxruZIEuEZEB3QKtwb/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T12:31:24Z"
  mac: ENC[AES256_GCM,data:oBvURpW4x8wj4ko+xWQGR9Dx5WIiCPazCB+d+LJdc/LapfERSS6Cxv4jq5YMKDPmLs+NjlOSx/2Xo5Xadu1V6t98xnyCnuu+aKGHkWO1EtrgK/kaYmbEjA1IIP/F7ajKmQDrULW+knz06UFAS3cUAQsv+mb0Yzry88f4GGjX5HY=,iv:5rZ/gAOgfPH9y/ZdPHzE7u9fncKCwb3FSyHM0KzH9O8=,tag:vHeRi2MVWvsqK3Fxu8MMxw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
