apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:tT7bhha6SVc45V0ZtZamuokADity3surF3qJH09mSShh1SolimWT1COV5ia11qAZjSKlmoTIp2MJqssI+fxS0+qEitdODCJScYOl3g2X/Mv1j/cj0kXwk9KAsOfg3ilY10seq26awwArJL2YXeoKnGZNQCzryl2ygkCFyz31SYavygm3CpRmnOFftB4l5LBeLX3QJX2fOSw/9NFtS6Wbif/WV2tOVlRNBGi68u5b90JM20Pk,iv:qJllZtsJ650wsxZ5nxtMFopKRBidPzSJq4rAj0noZcE=,tag:FJXPfeA4VIrJU1jjlt8GSg==,type:str]
sops:
  age:
    - recipient: age10tnmsw8l3xsg8ym5ed4x8zk606jq77jzudrehky98vf9jyw37gjqfn67fa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUDJsNmFBZFhkWlBqeDRX
        ZjVqYzIzNmR4WVRrUm96RXE5WTdXNm42ZUVNCjhiZ3Y1OFBCOTFubWFVZEUvbWZB
        dVJuaEdMNEEwT2FrUmJJdFA1MXhPUTQKLS0tIDhtTityRTQwNEFpZjh6bzNxcUtK
        enNnTXphUGplK1RSZ2FYRlMxTzVvdjgKA0oMGgyhEZkKtdyQuaKZb0uRfRp64S6F
        PL4m4MRFB7xnylLfaLat+0XcKuKL85WNra3Av6JfmneACUZ6IoR9ng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T12:20:29Z"
  mac: ENC[AES256_GCM,data:3RjXxW17z5dNXhyye1n0Fv9TY9qqKOiq3ngL8O3ypVaWL5iQ3hHSajpzmoyXMDe8rLsLFNbWuDRHsr/JavcEMCQEnClKqBlrWsgdI2tNFKAynPkXR9Pbh6erh1JokJIJ8nk+/xVx/URtWnLpmLKpkUefqzDRR0/FDDZfnMTJ0yI=,iv:KOljePsMPBxStmjBdO5TED65Jpey76Sdr7XdORg0Cz0=,tag:v6ypesNSL2mHRNljXYoZ3A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
