apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:kA2hUdCaGqowv2BUuS8P8q6GDbQSndOUdpV61KdSCCTUe+h4FC1F9YDJhRkke31VYJxnGto=,iv:nEMxImmABFpaDxG63IWTlZYSiZ1tacvDaJh3bsABDNU=,tag:XNp/UNyKzBHpvWhKE/g2mQ==,type:str]
sops:
  age:
    - recipient: age10tnmsw8l3xsg8ym5ed4x8zk606jq77jzudrehky98vf9jyw37gjqfn67fa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYis2dEphVXVmbmVwUkpm
        NWNwc2N0aVo5TVN3R2xXbWppRWtnUFNUNkJ3CjVId1Y2b3IxQ0liMldXR0pSZit1
        cks5QnF1WUxwMGF6OE5MTjZsWE5kVlUKLS0tIGg5V2Mzbk53RGlNV0V0cjNBTnIz
        bkQzVlJmUE1iaDVNRVl5cFM4R0FnS0EK282YxC/Pv9T3P1mjtBu6dQ+9RUNPFtP6
        YBtBrewWjDtvGkZ217pZH4FDTkOcDPYY9erxjXCSXHi2+f+uwwp4jQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T14:15:46Z"
  mac: ENC[AES256_GCM,data:rBY3qBa4ceH8K1GNrxUDueynVu2w4BgrFoKkLhue2FpkG6rc/dOT0midpXIugP5CCb5E83yEXbwdn4o5CrO9Zm4GAs4BoVTQG9n30QS7QIzOP0Sv7onLbpkeoVimi5pKIVKg+9fROCBVi/2bKDux1Jf+QWeANNGdsaoT4rnInfM=,iv:5RxbV9vpx4ppciuqZjtplEjeFGOmKS9fCE9rWuHNTHo=,tag:fgMMp4N/T6r3CqP5Yl1JKA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
