apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Cv175KwPLwIa1fl6zuVIVLncr9YyImcO+qAuq2v0XsQ9a4oztCQFhvbkwL+Oj16vxiT/YiA=,iv:wmeq+Qt6AIp6iFitszdsCmg0OADsUY/7YlHMQXOp0ug=,tag:/qKphpr6lP2tGUdrPH/GcQ==,type:str]
sops:
  age:
    - recipient: age10tnmsw8l3xsg8ym5ed4x8zk606jq77jzudrehky98vf9jyw37gjqfn67fa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveG0zL1VOTERRNDdGWDMw
        cml3R0Z6SHcranNqNmlsREt3MENiYjBTampZCmdYZUlGL25kWHIwOEFTYVdoM2NW
        VDdOdkc4WmFoZEgwNDd2cTVFNXFMK2cKLS0tIERydUlOTHE4OC9ReExMclAyS2Yr
        NUtxbEdic3ZmMDFHZnV6Qno0c1F5MTAKWikwFTThz8ycj8KnUgSv83SNd61Yu6GF
        uz5i3KD7LmGmNAAlU8YauJV0GUG9Bvv7lC8BsRwyAc7EtkIPEgmo2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T12:20:29Z"
  mac: ENC[AES256_GCM,data:/mp6JSvb3MUuP01nyO+UCTtvD1v4p30GPxcxycA677PxwDgTpqnfqCPvvfSBLnWHbgZZt7mzanZmdznadg4Q+mxYqxB5JXvxaun+Sjl+x246knVVSQbRPZx1SmfW11z9nLgh8pTOXV02nYtYeK4YgYo+gwKAQyOvC2bDT6GuEDo=,iv:ZrQLf1eV++POabdObKYcYedDb/28NKIiUxqj3KuJytA=,tag:EsQ1t/1KKGA4zJSAIxgG3A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
