apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:MNNj/KL4WjQrVVxV0yLzxzuFhQB8+tXth8GoRD3MltzY38q9GbIwwVpcPEtzwXKB5SO9dgo=,iv:sQbEDy0nOKIo6e9YnWM7NsOI9PCBmGqzTDAUKcflKJs=,tag:mFO+7tcJnWrx2Of6eSZ9Vw==,type:str]
sops:
  age:
    - recipient: age10tnmsw8l3xsg8ym5ed4x8zk606jq77jzudrehky98vf9jyw37gjqfn67fa
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUWVlSHZFRWhTSzBKMDJE
        Q09BQXF6aDdrY2t0Y0JTL2dUWVk1eGY0ZnpRCk1raW8yNDc4bnR1bk4xS2VydC8z
        TTI0RTgvVWNZeGMzUnFoNnV4ay9IODAKLS0tIDQvQjBMUGNBdkw2Mkd3a1JmVlVy
        WVI4dkt4dkpLVTBMK3NDZDdTcTIvdXMK1UMrxpJjdozHoFJds+NUmcY5g0Jz/yzc
        tmirJh1UEbfaY4tj8gla2frLvYihhL0gqNdPyUNtLaDsNjJ+1gKt/Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T12:31:23Z"
  mac: ENC[AES256_GCM,data:ohCZ7uKqNYysb7d8VKiE2js4POwXc3eg30OMODDyswfEi/6Fark5G1kVRoipPtSraPuhhLQDjNY3QKH6zAoDHe9IKSQUT6Jn7r00syqL4WDuu2WYKG7WflB7BLMZFSJBw/ShlZAB3r8ekQ/DOfR6X0TbwlDRe57ZNwn3ClcCBwg=,iv:PlhCav8lXyOP7phKaf/PxM0KX2U7XHTHQIuH1Ytblzs=,tag:oG2dAlAOt1Mlg16wETF/hA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
