---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.5.125:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.5.125"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "node1"
    ipAddress: "192.168.5.101"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/b2c39cfaec0508c46e30a90dc10041c3cd6942bed31654e43933f8c0e6b0e428
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "52:54:00:ad:35:53"
        dhcp: false
        addresses:
          - "192.168.5.101/24"
        routes:
          - gateway: "192.168.5.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.5.125"
  - hostname: "node2"
    ipAddress: "192.168.5.102"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/b2c39cfaec0508c46e30a90dc10041c3cd6942bed31654e43933f8c0e6b0e428
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "52:54:00:20:7f:2a"
        dhcp: false
        addresses:
          - "192.168.5.102/24"
        routes:
          - gateway: "192.168.5.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.5.125"
  - hostname: "node3"
    ipAddress: "192.168.5.103"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/b2c39cfaec0508c46e30a90dc10041c3cd6942bed31654e43933f8c0e6b0e428
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "52:54:00:29:14:04"
        dhcp: false
        addresses:
          - "192.168.5.103/24"
        routes:
          - gateway: "192.168.5.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.5.125"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-iscsi.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/machine-longhorn.yaml"
  - "@./patches/global/machine-longhorn-labels.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

