---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jackett-pv-test
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "3"
      staleReplicaTimeout: "30"
    volumeHandle: jackett-pv
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn