---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-pvs
  namespace: longhorn-system
spec:
  cron: "00 02 * * *"
  task: backup
  groups:
    - default
  retain: 3
  concurrency: 1
